USE project_musicstream;

CREATE TABLE nationalities (
    id_nationality INT AUTO_INCREMENT PRIMARY KEY,
    nationality VARCHAR(100) NOT NULL
);

-- Insert the nationalities
INSERT INTO nationalities (nationality) VALUES
('Afghan'),
('Albanian'),
('Algerian'),
('Argentine'),
('Argentinian'),
('Australian'),
('Austrian'),
('Bangladeshi'),
('Belgian'),
('Bolivian'),
('Batswana'),
('Botswanan'),
('Brazilian'),
('Bulgarian'),
('Cambodian'),
('Cameroonian'),
('Canadian'),
('Chilean'),
('Chinese'),
('Colombian'),
('Costa Rican'),
('Croatian'),
('Cuban'),
('Czech'),
('Danish'),
('Dominican'),
('Ecuadorian'),
('Egyptian'),
('Salvadorian'),
('Salvadoran'),
('English'),
('Estonian'),
('Ethiopian'),
('Fijian'),
('Finnish'),
('French'),
('German'),
('Ghanaian'),
('Greek'),
('Guatemalan'),
('Haitian'),
('Honduran'),
('Hungarian'),
('Icelandic'),
('Indian'),
('Indonesian'),
('Iranian'),
('Iraqi'),
('Irish'),
('Israeli'),
('Italian'),
('Jamaican'),
('Japanese'),
('Jordanian'),
('Kenyan'),
('Kuwaiti'),
('Lao'),
('Laotian'),
('Latvian'),
('Lebanese'),
('Libyan'),
('Lithuanian'),
('Malagasy'),
('Malaysian'),
('Malian'),
('Maltese'),
('Mexican'),
('Mongolian'),
('Moroccan'),
('Mozambican'),
('Namibian'),
('Nepalese'),
('Dutch'),
('New Zealander'),
('Nicaraguan'),
('Nigerian'),
('Norwegian'),
('Pakistani'),
('Panamanian'),
('Paraguayan'),
('Peruvian'),
('Filipino'),
('Polish'),
('Portuguese'),
('Romanian'),
('Russian'),
('Saudi'),
('Saudi Arabian'),
('Scottish'),
('Senegalese'),
('Serbian'),
('Singaporean'),
('Slovak'),
('South African'),
('South Korean'),
('Spanish'),
('Sri Lankan'),
('Swedish'),
('Swiss'),
('Syrian'),
('Taiwanese'),
('Tanzanian'),
('Thai'),
('Turkish'),
('Ugandan'),
('Ukrainian'),
('Emirati'),
('British'),
('American'),
('Uruguayan'),
('Venezuelan'),
('Vietnamese'),
('Welsh'),
('Yemeni'),
('Zambian'),
('Zimbabwean');

DROP table artistas;

	
